name-template: 'v$NEXT_PATCH_VERSION 🌟'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 New Features'
    labels:
      - feature
      - enhancement
  - title: '🐛 Bug Fixes'
    labels:
      - bug
      - fix
  - title: '🧰 Maintenance'
    labels:
      - chore
      - refactor
      - documentation

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
change-title-escapes: '\<*_&'

template: |
  ## Changes
  $CHANGES
